[package]

name = "burn-launcher"
version = "0.1.0"
edition = "2021"

[dependencies]

burn = { workspace = true }
burn-wgpu = "0.20.1"
clap = { workspace = true }
crossterm = { workspace = true }
hf-hub = { workspace = true }
indicatif = { workspace = true }
log = { workspace = true }
ratatui = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }

# llama-burn
async-stream = "0.3.6"
axum = "0.8.8"
base64 = { version = "0.22.1", optional = true }
burn-onnx = "0.21.0-pre.1"
burn-store = { version = "0.20.1", features = ["std", "burnpack"] }
dirs = { workspace = true, optional = true }
futures-util = "0.3.32"
itertools = { version = "0.14.0", default-features = false, features = ["use_alloc"] }
rand = { version = "0.10.0", default-features = false, features = ["alloc", "std_rng"] }
rustc-hash = { version = "1.1.0", optional = true }
sysinfo = { workspace = true }
tiktoken-rs = { version = "0.10.0", optional = true }
tokenizers = { version = "0.22.2", default-features = false, features = ["onig"], optional = true }
tokio-stream = "0.1.18"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[features]

cuda = []
default = ["llama3", "hf-tokenizer", "pretrained", "import"]
hf-tokenizer = ["dep:tokenizers"]
import = ["burn-store/pytorch", "burn-store/safetensors"]
llama3 = ["dep:tiktoken-rs", "dep:rustc-hash", "dep:base64"]
pretrained = ["dirs"]
tch-gpu = []
