imports = [
  "language.go"
]

[devshell]

name = "golang"

motd = "Development Shell for Golang"

# Use `nix search nixpkgs <term>` to find package names.
packages = [

  "diffutils", # used by golangci-lint
  "goreleaser",
  "mdbook",
  "mdsh",
  "webfs",
  "hyperfine",

]

[[commands]]
help = "prints hello"
name = "hello"
command = "echo hello"

[[commands]]
package = "nixpkgs-fmt"
category = "formatters"

[[commands]]
help = "github utility"
name = "hub"
package = "gitAndTools.hub"
category = "utilites"

[[commands]]
help = "golang linter"
package = "golangci-lint"
category = "linters"
