##################################################
# SOPS configuration.
#
# NOTES:
#
#    nix-shell -p sops --run "sops secrets/keystore.yaml"
#
##################################################

keys:
  # Users (AGE, local)
  - &admin_mahdtech_nuc_age age1t6p4lhlmqk7gkmp4hxccnqf5g0qu2xecef04hyn4cxlc3gs8fecqhvxmfg

  # Users (AGE)
  - &admin_mahdtech_1password_age age127h9hx8p5tc5chldkhek9a7f4qje25qmngd99y4unl3tyzayr3yq0jp3xn

  # Users (GPG)
  - &admin_mahdtech_yubikey_gpg C8007116A87DB942310AD5FC218703275A091016

  # Systems (AGE)
  - &system_jons_age age1l4zs9vmtnsck7t2nqhqt7rnpske9eajlwqr5zr2ggjrf2cfjds4sx6y2rf
  - &system_nuc_age age12m5c674qsrm4l8kszzm9mtfcc6x4gf0lj2dn8m7pau2alafduvmsmffndy

  # Systems (AGE, Hypervisors)
  - &system_hypervisor_1_age age17rjkqy28e0kkk05egnexxgwdrw7lmuyamu4slrevqqwfqa38tesq7r0e07
  - &system_hypervisor_2_age age1qte2qxa430rxrkluwkte6m5aswv677y6e6q8hqj5f44lkc0459esq8vyz3
  - &system_hypervisor_3_age age1k636za8dsevlkpgk3srjumu2ztpzx4urava8kk297rnsu0flhpcs2gp02p
  - &system_hypervisor_4_age age1c0t3c9ccpx596f0k4fgxpldqg0a83khez3jxf9r3x80lsqw64s2qtugca7

  # Systems (GPG)
  - &system_jons_gpg 058a30ccc32bdbd8c1f83f913724ced5ed967743
  - &system_nuc_gpg 67e8f2311d5b7f5177852cfcb82d6aff07651e96

  # Systems (GPG, Hypervisors)
  - &system_hypervisor_1_gpg c43b5a46ce32e067759f3e3de5bb85adfc127a22
  - &system_hypervisor_2_gpg c53378b986854f6f766400b7ce0e0e1c6190fb9f
  - &system_hypervisor_3_gpg c11cb07960e989964b0e3b1dfec9424778b55a19
  - &system_hypervisor_4_gpg 2a103f0194cb2e495d8454ca77f992e1a386c4e2

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          # Local
          - *admin_mahdtech_nuc_age
          # Users
          - *admin_mahdtech_1password_age
          # Systems
          - *system_jons_age
          - *system_nuc_age
          # Hypervisors
          - *system_hypervisor_1_age
          - *system_hypervisor_2_age
          - *system_hypervisor_3_age
          - *system_hypervisor_4_age

      - pgp:
          # Users
          - *admin_mahdtech_yubikey_gpg
          # Systems
          - *system_jons_gpg
          - *system_nuc_gpg
          # Hypervisors
          - *system_hypervisor_1_gpg
          - *system_hypervisor_2_gpg
          - *system_hypervisor_3_gpg
          - *system_hypervisor_4_gpg
