##################################################
# SOPS configuration.
#
# NOTES:
#
#    nix-shell -p sops --run "sops secrets/keystore.yaml"
#
##################################################

keys:
  # Users (AGE, local)
  - &admin_mahdtech_nuc_age age1t6p4lhlmqk7gkmp4hxccnqf5g0qu2xecef04hyn4cxlc3gs8fecqhvxmfg

  # Users (AGE)
  - &admin_mahdtech_1password_age age127h9hx8p5tc5chldkhek9a7f4qje25qmngd99y4unl3tyzayr3yq0jp3xn

  # Users (GPG)
  - &admin_mahdtech_yubikey_gpg C8007116A87DB942310AD5FC218703275A091016

  # Systems (AGE)
  - &system_jons_age age1l4zs9vmtnsck7t2nqhqt7rnpske9eajlwqr5zr2ggjrf2cfjds4sx6y2rf
  - &system_nuc_age age12m5c674qsrm4l8kszzm9mtfcc6x4gf0lj2dn8m7pau2alafduvmsmffndy

  # Systems (AGE, Hypervisors)
  - &system_hypervisor_1_age age15yruthjnsterawg009na6th6v4avvg47u5el5e5a56caqgsuavysjktv4j
  - &system_hypervisor_2_age age1r5fxhn58f97rgvd6tt2lz0ytslyy459y5f575f3hp40phgervqcs7ac4cd
  - &system_hypervisor_3_age age1ulw0e6kpcwx4axtcmwz0k2678q75hx5wv8ug3wpcahlhq8uqcflsudkafj
  - &system_hypervisor_4_age age16zdwcfdyzg8anxz3svtudcw9pzfdp9kfg4dh0nvnpaquedugz5wqffv0l9

  # Systems (GPG)
  - &system_jons_gpg 058a30ccc32bdbd8c1f83f913724ced5ed967743
  - &system_nuc_gpg 67e8f2311d5b7f5177852cfcb82d6aff07651e96

  # Systems (GPG, Hypervisors)
  - &system_hypervisor_1_gpg dc271f6cf785325cd7c002b4ab388986289b455e
  - &system_hypervisor_2_gpg f55e76e81e86b25bdd15b3df61af853a2f0e4439
  - &system_hypervisor_3_gpg 37fd7b3637d400afb2565dd30ac59119c8c71bd9
  - &system_hypervisor_4_gpg 8707f6d1596deeb505ceab429feb18f2f06aeb56

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      #####################################################################
      # NOTE: Do NOT include the '-' before more than 1 key type.
      #       This will cause sops to require multiple keys (shamir secret sharing)
      #       to decrypt a secret, which breaks normal sops-nix usage.
      #####################################################################
      - age:
          # Local
          - *admin_mahdtech_nuc_age
          # Users
          - *admin_mahdtech_1password_age
          # Systems
          - *system_jons_age
          - *system_nuc_age
          # Hypervisors
          - *system_hypervisor_1_age
          - *system_hypervisor_2_age
          - *system_hypervisor_3_age
          - *system_hypervisor_4_age
        pgp:
          # Users
          - *admin_mahdtech_yubikey_gpg
          # Systems
          - *system_jons_gpg
          - *system_nuc_gpg
          # Hypervisors
          - *system_hypervisor_1_gpg
          - *system_hypervisor_2_gpg
          - *system_hypervisor_3_gpg
          - *system_hypervisor_4_gpg
