#########################
# SOPS configuration.
#########################

keys:
  - &admin_mahdtech_age X
  - &admin_mahdtech_gpg X

creation_rules:

  - path_regex: secrets/[^/]+\.yaml$
    key_groups:

    - pgp:
      - *admin_mahdtech_gpg

    - age:
      - *admin_mahdtech_age

