##################################################
# SOPS configuration.
#
# NOTES:
#
#    nix-shell -p sops --run "sops secrets/keystore.yaml"
#
##################################################

keys:
  # Users (AGE)
  - &admin_mahdtech_1password_age age127h9hx8p5tc5chldkhek9a7f4qje25qmngd99y4unl3tyzayr3yq0jp3xn
  - &admin_mahdtech_nuc_age age1g9watu56msn7xlqfsxhteppv7uvrm9wte7zn7lhul4nw9y7pys9s6wldan

  # Users (GPG)
  - &admin_mahdtech_gpg 521A973C9426E8F4EE1C48FB3E520D84C0F43391

  # Systems (AGE)
  - &system_jons_age age16juxmyv5728eyr3sw45ycg8wj5lzl3mqekwz2lx7r2ykmqr9g3lsm5zt8n
  - &system_kasm001_age age13wqvdp74vkkjqv9mruc06qene64rfzpm4wkemnpjxkgpmyac8v6q295fdz
  - &system_nuc_age age1atpe6jwhjgzajhpn9ky28d36tedm6ccu2t2w4vna78k7kwkwwycsprq800
  - &system_penguin_age age14qny4gehy8fkga9vha5khn26ywuutm5d3w5urawwaz68pr5py5nsl6xj8u

  # Systems (GPG)
  - &system_jons_gpg 008fae6072d5753c273de5f80ae595eeb3d73fbd
  - &system_nuc_gpg 3427c11a2069c301130939caeef52927134a6d84
  - &system_penguin_gpg 21ba9b4c175dda9f5f3519532e51b9ac938f3a69

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          # Users
          - *admin_mahdtech_gpg
          # Systems
          - *system_jons_gpg
          - *system_nuc_gpg
          - *system_penguin_gpg

        age:
          # Users
          - *admin_mahdtech_nuc_age
          - *admin_mahdtech_1password_age
          # Systems
          - *system_jons_age
          - *system_kasm001_age
          - *system_nuc_age
          - *system_penguin_age
