#########################
# SOPS configuration.
#########################

keys:
  # Users
  #- &admin_mahdtech_age X
  - &admin_mahdtech_gpg 521A973C9426E8F4EE1C48FB3E520D84C0F43391
  # Systems

creation_rules:

  - path_regex: secrets/[^/]+\.yaml$
    key_groups:

    - pgp:
      - *admin_mahdtech_gpg

    - age:
      - *admin_mahdtech_age
