[default]

locale = "en-au"

extend-ignore-re = [
    "^[ \t]*-----BEGIN PGP PUBLIC KEY BLOCK-----.*^[ \t]*-----END PGP PUBLIC KEY BLOCK-----",
    "^[ \t]*initialHashedPassword[ \t]*=[ \t]*.*$"
]

[default.extend-words]

normalization = "normalization"
recognize = "recognize"
authorized = "authorized"
authorised = "authorised"
center = "center"
cros = "cros"
customizations = "customizations"
guage = "guage"
hashi = "hashi"
hashicorp = "hashicorp"

[files]

ignore-vcs = true

extend-exclude = [
  "*.drawio",
  ".devenv",
  ".direnv",
  ".git",
  "secrets",
  "vendor"
]
