[default]

locale = "en-au"

extend-ignore-re = [
    "^[ \t]*-----BEGIN PGP PUBLIC KEY BLOCK-----.*^[ \t]*-----END PGP PUBLIC KEY BLOCK-----"
]

[default.extend-words]

center = "center"
customizations = "customizations"
guage = "guage"
hashi = "hashi"
hashicorp = "hashicorp"
cros = "cros"

[files]

ignore-vcs = true

extend-exclude = [
  "*.drawio",
  ".devenv",
  ".direnv",
  ".git",
  "vendor"
]
