# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = ["nvme" "sd_mod" "thunderbolt" "usb_storage" "usbhid" "xhci_pci"];

      kernelModules = [];
    };

    kernelModules = ["kvm-intel"];

    extraModulePackages = [];
  };

  fileSystems."/" =
    { device = "zpool/root";
      fsType = "zfs";
      neededForBoot = true;
      options = ["zfsutil" "X-mount.mkdir"];
    };

  fileSystems."/boot" =
    { device = "zpool/boot";
      fsType = "zfs";
      neededForBoot = true;
      options = ["zfsutil" "X-mount.mkdir"];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/ACD0-FD4A";
      fsType = "vfat";
      neededForBoot = true;
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "zpool/home";
      fsType = "zfs";
      neededForBoot = true;
      options = ["zfsutil" "X-mount.mkdir"];
    };

  fileSystems."/nix" =
    { device = "zpool/nix";
      fsType = "zfs";
      neededForBoot = true;
      options = ["zfsutil" "X-mount.mkdir"];
    };

  fileSystems."/var" =
    { device = "zpool/var";
      fsType = "zfs";
      neededForBoot = true;
      options = ["zfsutil" "X-mount.mkdir"];
    };

  fileSystems."/tmp" =
    { device = "zpool/tmp";
      fsType = "zfs";
      neededForBoot = true;
      options = ["zfsutil" "X-mount.mkdir"];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp61s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  
  hardware = {
    cpu.intel.updateMicrocode =
      lib.mkDefault config.hardware.enableRedistributableFirmware;

    enableRedistributableFirmware = true;
  };

}
