"""Materialize Beszel's inventory from systemd credentials, never Nix-store secrets."""

import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile


def publish(path, content):
    descriptor, temporary = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}-")
    try:
        with os.fdopen(descriptor, "w") as output:
            output.write(content)
        os.replace(temporary, path)
    finally:
        Path(temporary).unlink(missing_ok=True)


def prepare(manifest, directory, credentials, keygen):
    systems = []
    for name, member in manifest["systems"].items():
        token = (credentials / member["tokenCredential"]).read_text().strip()
        if not token or any(character.isspace() for character in token):
            raise ValueError(f"Invalid registration token for {name}")
        users = member["users"] or [os.environ.get("USER_EMAIL", "")]
        if not all(users):
            raise ValueError("Set inventory users or provide bootstrap USER_EMAIL")
        systems.append({"name": name, "host": member["host"], "port": member["port"],
                        "users": users, "token": token})
    private_key = None
    if manifest["privateKey"]:
        key_file = credentials / "hub-private-key"
        # Secret text fields can lose the final newline required by OpenSSH.
        private_key = key_file.read_text().rstrip("\r\n") + "\n"
        with tempfile.NamedTemporaryFile(mode="w", prefix="beszel-key-") as candidate:
            candidate.write(private_key)
            candidate.flush()
            subprocess.run([keygen, "-y", "-P", "", "-f", candidate.name], check=True,
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    marker = directory / ".nixos-managed-inventory"
    if not manifest["managed"] and marker.exists():
        (directory / "config.yml").unlink(missing_ok=True)
        marker.unlink()
    if private_key is None and not systems:
        return
    directory.mkdir(mode=0o700, parents=True, exist_ok=True)
    if private_key is not None:
        publish(directory / "id_ed25519", private_key)
    if systems:
        # JSON is valid YAML; serialization keeps runtime credentials out of templates.
        publish(directory / "config.yml", json.dumps({"systems": systems}) + "\n")
        publish(marker, "Generated by NixOS\n")


if __name__ == "__main__":
    try:
        prepare(json.loads(Path(sys.argv[1]).read_text()), Path(sys.argv[2]),
                Path(os.environ.get("CREDENTIALS_DIRECTORY", "/nonexistent")), sys.argv[3])
    except (OSError, ValueError, subprocess.CalledProcessError):
        sys.exit("Beszel preparation failed: check runtime credentials and inventory; previous files were retained until validation completed.")
