#!/usr/bin/env nix-shell
#shellcheck disable=SC1008
#!nix-shell -i bash -p bash curl jq gnused gnugrep nix cacert
#
# Codex Nix Update Script
# Bumps default.nix to the latest upstream release (or the version given as
# $1, e.g. "0.153.4"), then refreshes every pinned hash:
#   - src hash (fetchFromGitHub)
#   - librusty_v8 / src_binding pins (from upstream's Cargo.lock)
#   - cargoHash (via a fake-hash build against this repo's pinned nixpkgs)

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"
REPO_ROOT="$(git rev-parse --show-toplevel)"
HOST="${HOST_NAME:-$(hostname)}"

gh_curl() {
	curl ${GITHUB_TOKEN:+-u ":$GITHUB_TOKEN"} -fsSL "$@"
}

if [ $# -ge 1 ]; then
	VERSION="$1"
else
	VERSION=$(gh_curl "https://api.github.com/repos/openai/codex/releases/latest" |
		jq -r '.tag_name' | sed 's/^rust-v//')
fi
TAG="rust-v$VERSION"

CURRENT=$(sed -nE 's/^  version = "(.*)";$/\1/p' default.nix)
if [ "$CURRENT" == "$VERSION" ]; then
	echo "codex: already at $VERSION"
	exit 0
fi
echo "codex: $CURRENT -> $VERSION"

# --- src hash ---------------------------------------------------------------
echo "codex: prefetching source"
SRC_HASH=$(nix-prefetch-url --unpack --type sha256 \
	"https://github.com/openai/codex/archive/refs/tags/$TAG.tar.gz" 2>/dev/null |
	xargs nix-hash --to-sri --type sha256)

sed -i -E \
	-e "s|^  version = \".*\";$|  version = \"$VERSION\";|" \
	-e "s|^    hash = \"sha256-.*\";$|    hash = \"$SRC_HASH\";|" \
	default.nix

# --- librusty_v8 pins ---------------------------------------------------------
V8_VERSION=$(gh_curl "https://github.com/openai/codex/raw/$TAG/codex-rs/Cargo.lock" |
	grep --after-context 5 'name = "v8"' | sed -nE 's/^version = "(.*)"$/\1/p')
V8_CURRENT=$(sed -nE 's/^  version = "(.*)";$/\1/p' librusty_v8.nix)

if [ "$V8_CURRENT" == "$V8_VERSION" ]; then
	echo "librusty_v8: already at $V8_VERSION"
else
	echo "librusty_v8: $V8_CURRENT -> $V8_VERSION"
	V8_BASE="https://github.com/denoland/rusty_v8/releases/download/v$V8_VERSION"
	prefetch() { nix-prefetch-url --type sha256 "$V8_BASE/$1" 2>/dev/null; }

	cat >librusty_v8.nix <<NIX
# auto-generated by update.sh -- DO NOT EDIT!
{ fetchLibrustyV8 }:

fetchLibrustyV8 {
  version = "$V8_VERSION";
  shas = {
    x86_64-linux = "$(prefetch librusty_v8_release_x86_64-unknown-linux-gnu.a.gz)";
    aarch64-linux = "$(prefetch librusty_v8_release_aarch64-unknown-linux-gnu.a.gz)";
    riscv64-linux = "$(prefetch librusty_v8_release_riscv64gc-unknown-linux-gnu.a.gz)";
    aarch64-darwin = "$(prefetch librusty_v8_release_aarch64-apple-darwin.a.gz)";
  };
}
NIX

	cat >librusty_v8_src_binding.nix <<NIX
# auto-generated by update.sh -- DO NOT EDIT!
{ fetchLibrustyV8SrcBinding }:

fetchLibrustyV8SrcBinding {
  version = "$V8_VERSION";
  shas = {
    x86_64-linux = "$(prefetch src_binding_release_x86_64-unknown-linux-gnu.rs)";
    aarch64-linux = "$(prefetch src_binding_release_aarch64-unknown-linux-gnu.rs)";
    riscv64-linux = "$(prefetch src_binding_release_riscv64gc-unknown-linux-gnu.rs)";
    aarch64-darwin = "$(prefetch src_binding_release_aarch64-apple-darwin.rs)";
  };
}
NIX
fi

# --- cargoHash --------------------------------------------------------------
# Build the vendored deps with a fake hash and harvest the real one from the
# mismatch error. Only the cargo vendor step runs, not the full compile.
echo "codex: computing cargoHash (fake-hash build)"
FAKE="sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
sed -i -E "s|^  cargoHash = \"sha256-.*\";$|  cargoHash = \"$FAKE\";|" default.nix

set +e
BUILD_LOG=$(nix --extra-experimental-features 'nix-command flakes' build --no-link \
	--accept-flake-config --impure --expr \
	"let pkgs = (builtins.getFlake \"$REPO_ROOT\").nixosConfigurations.\"$HOST\".pkgs;
	 in (pkgs.callPackage $PWD { }).cargoDeps" 2>&1)
set -e

CARGO_HASH=$(echo "$BUILD_LOG" | sed -nE 's/^\s*got:\s*(sha256-\S+).*$/\1/p' | head -n1)
if [ -z "$CARGO_HASH" ]; then
	echo "codex: failed to extract cargoHash from build output:" >&2
	echo "$BUILD_LOG" | tail -n 30 >&2
	exit 1
fi
sed -i -E "s|^  cargoHash = \"sha256-.*\";$|  cargoHash = \"$CARGO_HASH\";|" default.nix

echo "codex: updated to $VERSION"
echo "  src hash:   $SRC_HASH"
echo "  cargoHash:  $CARGO_HASH"
echo "  librusty_v8: $V8_VERSION"
