[package]
name = "ranger-api"
version = "0.1.0"
edition = "2021"

[dependencies]
ranger-core = { path = "../ranger-core" }
axum = { workspace = true }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true }
serde_json = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
log = { workspace = true }
utoipa-swagger-ui = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tokio-stream = { workspace = true }
