{
  imports = [
    ./alacritty.nix
    ./bash.nix
    ./command-not-found.nix
    ./dconf.nix
    ./direnv.nix
    ./fzf.nix
    ./git.nix
    ./gpg.nix
    ./htop.nix
    ./neovim.nix
    #./python.nix
    ./sops-nix.nix
    ./ssh.nix
    ./starship.nix
    ./vim.nix
    ./vscode.nix
    ./wakatime.nix
    ./work.nix
  ];
}
