- name: "Gemma 4 31B Instruct (Image-Text)"
  vendor: "Google"
  collection: "Gemma 4"
  engine: "gemma4"
  repo_id: "google/gemma-4-31B-it"
  weight_file: "model.safetensors"
  required_ram_gb: 34.0

- name: "Gemma 4 31B Base (Image-Text)"
  vendor: "Google"
  collection: "Gemma 4"
  engine: "gemma4"
  repo_id: "google/gemma-4-31B"
  weight_file: "model.safetensors"
  required_ram_gb: 34.0

- name: "Gemma 4 26B-A4B Instruct (Image-Text)"
  vendor: "Google"
  collection: "Gemma 4"
  engine: "gemma4"
  repo_id: "google/gemma-4-26B-A4B-it"
  weight_file: "model.safetensors"
  required_ram_gb: 28.0

- name: "Gemma 4 26B-A4B Base (Image-Text)"
  vendor: "Google"
  collection: "Gemma 4"
  engine: "gemma4"
  repo_id: "google/gemma-4-26B-A4B"
  weight_file: "model.safetensors"
  required_ram_gb: 28.0

- name: "Gemma 4 E4B Instruct (Any-to-Any)"
  vendor: "Google"
  collection: "Gemma 4"
  engine: "gemma4"
  repo_id: "google/gemma-4-E4B-it"
  weight_file: "model.safetensors"
  required_ram_gb: 5.0

- name: "Gemma 4 E4B Base (Any-to-Any)"
  vendor: "Google"
  collection: "Gemma 4"
  engine: "gemma4"
  repo_id: "google/gemma-4-E4B"
  weight_file: "model.safetensors"
  required_ram_gb: 5.0

- name: "Gemma 4 E2B Instruct (Any-to-Any)"
  vendor: "Google"
  collection: "Gemma 4"
  engine: "gemma4"
  repo_id: "google/gemma-4-E2B-it"
  weight_file: "model.safetensors"
  required_ram_gb: 3.0

- name: "Gemma 4 E2B Base (Any-to-Any)"
  vendor: "Google"
  collection: "Gemma 4"
  engine: "gemma4"
  repo_id: "google/gemma-4-E2B"
  weight_file: "model.safetensors"
  required_ram_gb: 3.0
