---
name: Nix Flake check

on:
  push:
    branches:
      - trunk

  pull_request:
    branches:
      - "trunk"

permissions:
  contents: read

env:
  NIXPKGS_ALLOW_INSECURE: 1
  NIXPKGS_ALLOW_UNFREE: 1
  NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM: 1

jobs:
  nix:
    runs-on: ubuntu-latest

    steps:
      - id: checkout_repository
        name: Checkout Repository
        uses: actions/checkout@v7
        with:
          lfs: false
          submodules: recursive

      - id: free_disk_space
        name: Free Disk Space
        uses: ./.github/actions/free-disk-space

      - id: setup_qemu
        name: Setup QEMU
        uses: docker/setup-qemu-action@v4

      - id: install_nix
        name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux

      - id: enable_cachix
        name: "Enable Cachix ❄️"
        uses: cachix/cachix-action@v17
        if: ${{ vars.CACHIX_CACHE_NAME != '' }}
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          useDaemon: true
          skipPush: false

      - id: test_devenv
        name: Test Devenv
        run: >-
          nix develop
          --accept-flake-config
          --impure
          .#default
          --command
          devenv test

      - id: check_flake
        name: Check Nix Flake
        run: >-
          nix flake check
          --accept-flake-config
          --no-eval-cache
          --all-systems
          --impure
          --keep-going
          --verbose

      - id: check_statix
        name: Check Statix
        run: nix run nixpkgs#statix -- check
