---
name: Nix Flake check

on:
  push:
    branches:
      - "trunk"

  pull_request:
    branches:
      - "trunk"

env:
  NIXPKGS_ALLOW_UNFREE: 1
  RUST_BACKTRACE: 1

jobs:
  nix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v19

      - name: Nix Flake check
        run: >-
          nix flake check
          --no-build
          --refresh
          --keep-going
          --verbose
          --impure

      - name: Statix check
        run: nix run nixpkgs#statix -- check
