---
name: Nix Flake check

on:
  push:
    branches:
      - trunk

  pull_request:
    branches:
      - "trunk"

permissions:
  contents: read

env:
  NIXPKGS_ALLOW_UNFREE: 1
  RUST_BACKTRACE: 1

jobs:
  nix:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
          submodules: recursive

      - id: install_nix
        name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v29

      - id: cachix
        name: "Enable Cachix ❄️"
        uses: cachix/cachix-action@v15
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          useDaemon: true
          skipPush: false

      - id: cache
        name: Magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Nix Flake check
        run: >-
          nix flake check
          --no-build
          --refresh
          --keep-going
          --verbose
          --impure

      - name: Statix check
        run: nix run nixpkgs#statix -- check
