name: Nix Flake update

on:

  schedule:
    - cron: "0 0 * * 0"

  workflow_dispatch:

permissions:
  contents: write

env:
  NIXPKGS_ALLOW_UNFREE: 1

jobs:

  nix:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v18

      #- name: Update flake.lock
      #  uses: DeterminateSystems/update-flake-lock@v15

      - name: Nix Flake update
        run: >
          nix flake update
          --verbose

      - name: Update flake.lock
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update flake.lock
          branch: trunk
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: Nix Flake Bot
          commit_author: Nix Flake Bot <actions@github.com>
          skip_dirty_check: false
          skip_fetch: true
