---
name: Nix Flake check

on:
  push:
    branches:
      - trunk

  pull_request:
    branches:
      - "trunk"

permissions:
  contents: read

env:
  NIXPKGS_ALLOW_UNFREE: 1
  RUST_BACKTRACE: 1

  CACHIX_CACHE_NAME: salt-labs

jobs:
  nix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v27

      - id: cachix
        name: "Enable Cachix ❄️"
        uses: cachix/cachix-action@v15
        with:
          name: ${{ env.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Nix Flake check
        run: >-
          nix flake check
          --no-build
          --refresh
          --keep-going
          --verbose
          --impure

      - name: Statix check
        run: nix run nixpkgs#statix -- check
